spring.application.name: "WIMF"

server.port: 8092

spring:
  datasource:
    url: jdbc:h2:mem:wimf;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect